program prjPedidos;

uses
  Vcl.Forms,
  untPrincipal in 'untPrincipal.pas' {frmPrincipal},
  untBiblioteca in 'untBiblioteca.pas',
  untSplash in 'untSplash.pas' {frmSplash},
  PedidoUsuariosVO in '..\VO\PedidoUsuariosVO.pas',
  PedidoUsuarioController in '..\Controller\PedidoUsuarioController.pas',
  Vcl.Themes,
  Vcl.Styles,
  PedidoEmpresasVO in '..\VO\PedidoEmpresasVO.pas',
  PedidoProdutosVO in '..\VO\PedidoProdutosVO.pas',
  untExportacaoDeProdutos in 'untExportacaoDeProdutos.pas' {frmExportacaoDeProdutos},
  untSQLs in 'untSQLs.pas' {frmSQLs},
  PedidoSqlVO in '..\VO\PedidoSqlVO.pas',
  PedidoSqlController in '..\Controller\PedidoSqlController.pas',
  untConexao in 'untConexao.pas' {frmConexao},
  PedidoFuncionariosVO in '..\VO\PedidoFuncionariosVO.pas',
  PedidoFuncionariosController in '..\Controller\PedidoFuncionariosController.pas',
  PedidoFormaPagamentoVO in '..\VO\PedidoFormaPagamentoVO.pas',
  PedidoClientesVO in '..\VO\PedidoClientesVO.pas',
  untExportacaoDeClientes in 'untExportacaoDeClientes.pas' {frmExportacaoDeClientes},
  PedidoClientesController in '..\Controller\PedidoClientesController.pas',
  untExportacaoDeFormaPagamento in 'untExportacaoDeFormaPagamento.pas' {frmExportacaoDeFormaPagamento},
  PedidoFormaPagamentoController in '..\Controller\PedidoFormaPagamentoController.pas',
  PedidoConexaoVO in '..\VO\PedidoConexaoVO.pas',
  PedidoConexaoController in '..\Controller\PedidoConexaoController.pas',
  untExportacaoDeFuncionarios in 'untExportacaoDeFuncionarios.pas' {frmExportacaoDeFuncionarios},
  untPedidos in 'untPedidos.pas' {frmPedidos},
  PedidoProdutosController in '..\Controller\PedidoProdutosController.pas',
  untPesquisarFormaPG in 'untPesquisarFormaPG.pas' {frmPesquisarFormaPG},
  BaseLocalClientesVO in '..\VO\BaseLocalClientesVO.pas',
  BaseLocalUnidadesVO in '..\VO\BaseLocalUnidadesVO.pas',
  BaseLocalProdutosVO in '..\VO\BaseLocalProdutosVO.pas',
  BaseLocalFuncionariosVO in '..\VO\BaseLocalFuncionariosVO.pas',
  BaseLocalUsuariosVO in '..\VO\BaseLocalUsuariosVO.pas',
  BaseLocalFormasPagamentoVO in '..\VO\BaseLocalFormasPagamentoVO.pas',
  BaseLocalVendaCabecalhoVO in '..\VO\BaseLocalVendaCabecalhoVO.pas',
  BaseLocalVendaDetalheVO in '..\VO\BaseLocalVendaDetalheVO.pas',
  BaseLocalTotalTipoPagtoVO in '..\VO\BaseLocalTotalTipoPagtoVO.pas',
  untMenuPrincipal in 'untMenuPrincipal.pas' {frmMenuPrincipal},
  BaseLocalVendaCabecalhoController in '..\Controller\BaseLocalVendaCabecalhoController.pas',
  BaseLocalVendaDetalheController in '..\Controller\BaseLocalVendaDetalheController.pas',
  BaseLocalTotalTipoPagtoController in '..\Controller\BaseLocalTotalTipoPagtoController.pas',
  BaseLocalClientesController in '..\Controller\BaseLocalClientesController.pas',
  BaseLocalFuncionariosController in '..\Controller\BaseLocalFuncionariosController.pas',
  BaseLocalUsuariosController in '..\Controller\BaseLocalUsuariosController.pas',
  untCadastrarUsuarios in 'untCadastrarUsuarios.pas' {frmCadastrarUsuarios},
  BaseLocalEmpresaController in '..\Controller\BaseLocalEmpresaController.pas',
  BaseLocalEmpresaVO in '..\VO\BaseLocalEmpresaVO.pas',
  untCadastrarProdutos in 'untCadastrarProdutos.pas' {frmCadastrarProdutos},
  untCadastrarUnidades in 'untCadastrarUnidades.pas' {frmCadastrarUnidades},
  untCadastrarFuncionarios in 'untCadastrarFuncionarios.pas' {frmCadastrarFuncionarios},
  untCadastrarEmpresa in 'untCadastrarEmpresa.pas' {frmCadastrarEmpresa},
  untCadastrarFormaPG in 'untCadastrarFormaPG.pas' {frmCadastrarFormaPG},
  untPesquisarEmpresa in 'untPesquisarEmpresa.pas' {frmPesquisarEmpresa},
  untPesquisarUnidades in 'untPesquisarUnidades.pas' {frmPesquisarUnidades},
  BaseLocalUnidadesController in '..\Controller\BaseLocalUnidadesController.pas',
  BaseLocalProdutosController in '..\Controller\BaseLocalProdutosController.pas',
  BaseLocalFormasPagamentoController in '..\Controller\BaseLocalFormasPagamentoController.pas',
  untExportacoes in 'untExportacoes.pas' {frmExportacoes},
  untCadastroParametros in 'untCadastroParametros.pas' {frmCadastroParametros},
  BaseLocalParametrosVO in '..\VO\BaseLocalParametrosVO.pas',
  BaseLocalParametrosController in '..\Controller\BaseLocalParametrosController.pas',
  BaseLocalPedidoCabecalhoVO in '..\VO\BaseLocalPedidoCabecalhoVO.pas',
  BaseLocalPedidoDetalheVO in '..\VO\BaseLocalPedidoDetalheVO.pas',
  BaseLocalPedidoCabecalhoController in '..\Controller\BaseLocalPedidoCabecalhoController.pas',
  BaseLocalPedidoDetalheController in '..\Controller\BaseLocalPedidoDetalheController.pas',
  BaseLocalSangriaVO in '..\VO\BaseLocalSangriaVO.pas',
  BaseLocalSuprimentoVO in '..\VO\BaseLocalSuprimentoVO.pas',
  BaseLocalSuprimentoController in '..\Controller\BaseLocalSuprimentoController.pas',
  BaseLocalSangriaController in '..\Controller\BaseLocalSangriaController.pas',
  untCadastrarSuprimento in 'untCadastrarSuprimento.pas' {frmCadastrarSuprimento},
  untCadastrarSangria in 'untCadastrarSangria.pas' {frmCadastrarSangria},
  untPreviaCaixa in 'untPreviaCaixa.pas' {frmPreviaCaixa},
  untObservacao in 'untObservacao.pas' {frmObservacao},
  untFechamentoCaixa in 'untFechamentoCaixa.pas' {frmFechamentoCaixa},
  untPainelRelatorios in 'untPainelRelatorios.pas' {frmPainelRelatorios},
  untRelProdutosMaisVendidos in 'untRelProdutosMaisVendidos.pas' {frmRelProdutosMaisVendidos},
  FiadoVO in '..\VO\FiadoVO.pas',
  FiadoController in '..\Controller\FiadoController.pas',
  untControleFiado in 'untControleFiado.pas' {frmControleFiado},
  untRecebimentoFiado in 'untRecebimentoFiado.pas' {frmRecebimentoFiado},
  untMovimentacaoCaixa in 'untMovimentacaoCaixa.pas' {frmMovimentacaoCaixa},
  untFinalizarVenda in 'untFinalizarVenda.pas' {frmFinalizarVenda},
  untEntradaXML in 'untEntradaXML.pas' {frmEntradaXML},
  untImportarXML in 'untImportarXML.pas' {frmImportarXML},
  FornecedoresVO in '..\VO\FornecedoresVO.pas',
  NotaEntradaCabecalhoVO in '..\VO\NotaEntradaCabecalhoVO.pas',
  NotaEntradaDetalheVO in '..\VO\NotaEntradaDetalheVO.pas',
  untAlterarPreco in 'untAlterarPreco.pas' {frmAlterarPreco},
  untCadastrarFornecedores in 'untCadastrarFornecedores.pas' {frmCadastrarFornecedores},
  untPesquisarFornecedores in 'untPesquisarFornecedores.pas' {frmPesquisarFornecedores},
  FornecedoresController in '..\Controller\FornecedoresController.pas',
  untEntradaManual in 'untEntradaManual.pas' {frmEntradaManual},
  untTelaAzul in 'untTelaAzul.pas' {frmTelaAzul},
  untCadastrarPromocao in 'untCadastrarPromocao.pas' {frmCadastrarPromocao},
  untCadastrarCategoria in 'untCadastrarCategoria.pas' {frmCadastrarCategoria},
  untPercDescontoPorCategoria in 'untPercDescontoPorCategoria.pas' {frmPercDescontoPorCategoria},
  untPercDescontoPromocao in 'untPercDescontoPromocao.pas' {frmPercDescontoPromocao},
  untCadastrarKit in 'untCadastrarKit.pas' {frmCadastrarKit},
  untInserirProdutoKit in 'untInserirProdutoKit.pas' {frmInserirProdutoKit},
  untPesquisarUsuarios in 'untPesquisarUsuarios.pas' {frmPesquisarUsuarios},
  untPequisarKitProdutos in 'untPequisarKitProdutos.pas' {frmPequisarKitProdutos},
  untCadastrarCaixas in 'untCadastrarCaixas.pas' {frmCadastrarCaixas},
  untPesquisarCaixas in 'untPesquisarCaixas.pas' {frmPesquisarCaixas},
  untPesquisarCategorias in 'untPesquisarCategorias.pas' {frmPesquisarCategorias},
  untPequisarEntradaManual in 'untPequisarEntradaManual.pas' {frmPequisarEntradaManual},
  untRelEstoque in 'untRelEstoque.pas' {frmRelEstoque},
  untRelFiado in 'untRelFiado.pas' {frmRelFiado},
  untCadastrarFidelidade in 'Fidelidade\untCadastrarFidelidade.pas' {frmCadastrarFidelidade},
  untIntegracaoFidelidade in 'Fidelidade\untIntegracaoFidelidade.pas',
  unitConfiguracoes in 'unitConfiguracoes.pas',
  untLogin in 'untLogin.pas' {frmLogin},
  untConsultarFidelidade in 'untConsultarFidelidade.pas' {frmConsultarFidelidade},
  untConsultarPagarFidelidade in 'untConsultarPagarFidelidade.pas' {frmConsultarPagarFidelidade},
  untCadastrarClientes in 'untCadastrarClientes.pas' {frmCadastrarClientes},
  untPesquisarClientes in 'untPesquisarClientes.pas' {frmPesquisarClientes},
  untPedidosPendentes in 'untPedidosPendentes.pas' {frmPedidosPendentes},
  untTelaDePedido in 'untTelaDePedido.pas' {frmTelaDePedido},
  untPesquisarProdutos in 'untPesquisarProdutos.pas' {frmPesquisarProdutos},
  untRelVendasPorFormaPG in 'untRelVendasPorFormaPG.pas' {frmRelVendasPorFormaPG},
  untRelVendasPorPeriodo in 'untRelVendasPorPeriodo.pas' {frmRelVendasPorPeriodo},
  untReimpressaoDeVendas in 'untReimpressaoDeVendas.pas' {frmReimpressaoDeVendas},
  untPadraoImpXml in 'untPadraoImpXml.pas' {frmPadraoImpXml},
  untPesquisarNCM in 'untPesquisarNCM.pas' {frmPesquisarNCM},
  untPesquisarCEST in 'untPesquisarCEST.pas' {frmPesquisarCEST},
  untCancelamentoDeVenda in 'untCancelamentoDeVenda.pas' {frmCancelamentoDeVenda},
  untExportarXML in 'untExportarXML.pas' {frmExportarXML},
  uIntegracaoBling in 'uIntegracaoBling.pas',
  untCadastroContas in 'untCadastroContas.pas' {frmCadastroContas},
  untPesquisarContasFinanceiras in 'untPesquisarContasFinanceiras.pas' {frmPesquisarContasFinanceiras},
  untLancamentoFinanceiro in 'untLancamentoFinanceiro.pas' {frmLancamentoFinanceiro},
  untConsultarLancFinanceiros in 'untConsultarLancFinanceiros.pas' {frmConsultarLancFinanceiros},
  untFiltrarLancFinanceiros in 'untFiltrarLancFinanceiros.pas' {frmFiltrarLancFinanceiros},
  untExportarVendasFinanceiro in 'untExportarVendasFinanceiro.pas' {frmExportarVendasFinanceiro},
  untLiquidarTitulos in 'untLiquidarTitulos.pas' {frmLiquidarTitulos},
  untQtdeParcelas in 'untQtdeParcelas.pas' {frmQtdeParcelas};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.Run;
end.
