object frmTelaAzul: TfrmTelaAzul
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 80
  BorderStyle = bsNone
  Caption = 'frmTelaAzul'
  ClientHeight = 348
  ClientWidth = 605
  Color = 16750899
  TransparentColor = True
  TransparentColorValue = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
end
